/*
 * Copyright Editions Lefebvre-Sarrut 2019
 */
package eu.lefebvre.sarrut.sie.xdprio.processes.params.lib;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URI;
import java.nio.charset.Charset;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Properties;

/**
 *
 * @author cmarchand
 */
public class ProcessParamsUtils {
    private Properties currentPP;
    private DateTimeFormatter formatter;
    
    public ProcessParamsUtils() {
        super();
        formatter = DateTimeFormatter.ISO_OFFSET_DATE_TIME;
    }
    
    /**
     * Parse uri and returns ProcessParams
     * @param uri Parameters to parse
     * @return Parameters to use
     * @throws IOException In case of problem.
     */
    public static ProcessParams parseParameterFile(URI uri) throws IOException {
        File f = new File(uri);
        Properties props = new Properties();
        props.loadFromXML(new FileInputStream(f));
        ProcessParams ret = new ProcessParams();
        for(String key: props.stringPropertyNames()) {
            ret.setParameter(key, props.getProperty(key));
        }
        return ret;
    }
    
    public void newProcessParams() {
        currentPP = new Properties();
    }
    public void addParameter(String parameterName, String parameterValue) {
        currentPP.setProperty(parameterName, parameterValue);
    }
    public void serializeParams(URI uri) throws IOException {
        File f = new File(uri);
        OutputStream os = new FileOutputStream(f);
        currentPP.storeToXML(os, "Generated by "+ProcessParamsUtils.class.getName()+" on "+formatter.format(OffsetDateTime.now()), Charset.forName("UTF-8"));
        currentPP=null;
    }
    
}
